Vertispan/j2clmavenplugin

- src/main/java/net/cardosi/mojo/TestMojo.java
it's difficult to analyze the test logs :
```
Starting ChromeDriver 76.0.3809.132 (fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}) on port 18372
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Sep 17, 2019 9:21:25 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```
i am proposing to run all tests and do a report of failed tests at the end. I also think it could be nice to to print test name and result during the run.
```
...
Test started: org.gwtproject.touch.client.TouchScrollTest
Starting ChromeDriver 76.0.3809.132 (fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}) on port 13813
Only local connections are …
```
> improved test log readability

- src/main/java/net/cardosi/mojo/ClosureBuildConfiguration.java
- src/main/java/net/cardosi/mojo/Hash.java
- src/main/java/net/cardosi/mojo/cache/CachedProject.java
- Hash.toString cached sha in hex form and never cleared when more stuff appended.
- Introduced helper append(String) to cleanup call-sites
- removed duplicate "Entrypoint" hashing
> Hash sha1 String fix and tidy up.

- pom.xml
- src/main/java/net/cardosi/mojo/TestMojo.java
Added test output to goal test. The test output will only be printed in case a test fails.   
I need to add the jsoup dependency to parse the html. It is using a MIT license. Is this ok, otherwise I need to search for something else. 
I will close the other PR (#12).
> added output in case of test failure for j2cl:test

- src/main/resources/junit.html
When running junit.html there is no info about the content encoding of
the html file. On os with no UTF-8 standard encoding (like Windows) this
results in interpreting the file with a non-UTF-8-Encoding. This is also
true for all referenced js-files which ends up in charset issues. This
commit fixes this issue by setting charset to UTF-8.
> Fix charset issue for test runner

- build-caching/pom.xml
This fix allows us to run j2cl-m-p on apple m1
> bump directory-watcher version to 0.15.0

- j2cl-tools/src/main/java/com/vertispan/j2cl/build/provided/BytecodeTask.java
- j2cl-tools/src/main/java/com/vertispan/j2cl/build/provided/JavacTask.java
- j2cl-tools/src/main/java/com/vertispan/j2cl/tools/Javac.java
This replaces commit 10c7ea5567 which added sources and resources
incorrectly to the classpath, preventing annotation processors from
being compiled, but it appeared to let them run correctly.
Fixes #87
> Correctly use source_path to offer resources to annotation processors

- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/TestMojo.java
This specifically fixes windows paths, so that /s appear in urls instead
of \s.
> Rebuild paths naively so that urls work

- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/WatchMojo.java
Previously this assumed the tag would be absent entirely, but it seems
that the tag can be present, without any value.
> Ensure the watch goal can pick up the webapp dir

- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/BundleJarTask.java
This fixes the hang by avoiding changing the hashcode of the task
instance, so it doesn't "disappear" in the HashSet.
> Reference defines before creating the task

- build-caching/src/main/java/com/vertispan/j2cl/build/Input.java
- build-caching/src/main/java/com/vertispan/j2cl/build/task/Input.java
- j2cl-maven-plugin/src/it/java-assertions/src/test/java/j2clsample/tests/MyTest.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/BundleJarTask.java
This cannot always be successful, given a dependency graph with enough
conflicts (such as changing direction of dependencies between releases),
but this will at least try to satisfy that any dependency which will be
present at runtime is listed in the correct order, based on other
runtime dependencies.
> BUNDLE_JAR must attempt to order JS files to satisfy dependencies

- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/JsZipBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/Closure.java
Sourcemaps again work consistently in BUNDLE, BUNDLE_JAR, and ADVANCED compilation levels.
Also avoids copying source content to output directories in some cases where it isn't required.
> Fix sourcemaps, improve closure logging

- build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java
- build-caching/src/main/java/com/vertispan/j2cl/build/WatchService.java
This fixes some issues when watching for changes in source directories.
> Ensure we don't consider directories when examining hash content

- j2cl-maven-plugin/src/it/hello-world-single/invoker.properties
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureTask.java
This deals with an apparent bug in closure-compiler where BUNDLE output
is attempted to be created without creating the directory, though other
compilation levels handle that. The simple hello-world project was a
good candidate to test this, so now it smoke tests all compilation
levels.
Fixes #110
> Create the parent directory of js output before calling closure

- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/AbstractBuildMojo.java
Gradle's "implementation" configuration for dependencies results in
published maven poms that are technically accurate for building
bytecode, but useless for building J2CL. To fix this, we interpret any
scope=runtime as if it says scope=compile.
A separate commit will include a test case to verify that the published
gwt modules in maven central work properly.
Fixes #126
> Treat pom scope=runtime as compile to make gradle poms usable

- j2cl-archetypes/j2cl-archetype-servlet/src/main/resources/archetype-resources/__rootArtifactId__-server/src/main/webapp/index.html
- j2cl-archetypes/j2cl-archetype-simple/src/main/resources/archetype-resources/src/main/webapp/index.html
- j2cl-maven-plugin/src/it/hello-world-reactor/app/src/main/webapp/index.html
- j2cl-maven-plugin/src/it/hello-world-single/src/main/webapp/index.html
- j2cl-maven-plugin/src/it/static-resources/src/main/java/com/example/public/index.html
- j2cl-maven-plugin/src/it/transitive-dependencies/app/src/main/webapp/index.html
- j2cl-tasks/src/main/resources/junit.html
Since HTML5 is now the standard, I believe the HTML files shouldn't use HTML4 anymore.
> Use HTML5 instead of HTML4

- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/JsZipBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/Closure.java
- pom.xml
This is the end of persistent input store, which was never used in this
iteration of j2cl-m-p. Instead, we'll be moving towards the typedast
feature, which closure-compiler uses to break its build into "stages".
This also fixes #157, by adding a new commit to our closure-compiler
feature of allowing sourcemaps in BUNDLE mode - contents loaded from a
different fs root will not try to relativize any longer.
> Update to latest closure v20220502-1

- j2cl-maven-plugin/src/it/annotation-processor-in-reactor/app/src/test/java/com/example/MyTestResources.java
- j2cl-maven-plugin/src/it/annotation-processor-in-reactor/app/src/test/java/com/example/ResourceTest.java
- j2cl-maven-plugin/src/it/annotation-processor-in-reactor/resources/src/main/resources/test-res-in-root-dir.txt
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/AbstractBuildMojo.java
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/TestMojo.java
Fix to ignore maven apt generated files with scope test (directory generated-test-sources/test-annotations)
> ignore-maven-apt-test-annotations

- build-caching/src/main/java/com/vertispan/j2cl/build/PropertyTrackingConfig.java
- build-caching/src/main/java/com/vertispan/j2cl/build/TranslationsFileConfiguration.java
- build-caching/src/main/java/com/vertispan/j2cl/build/task/Config.java
- j2cl-maven-plugin/src/it/translationsfile/pom.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_cz.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_cz_auto.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_cz_in_resource.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_de_in_java_package-auto.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_executions.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_fr.xml
- j2cl-maven-plugin/src/it/translationsfile/tests/pom_fr_meta_inf.xml
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/BuildMojo.java
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/TestMojo.java
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/TranslationsFileConfig.java
- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/Xpp3DomConfigValueProvider.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/TranslationsFileProcessor.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/Closure.java
this PR bring ability to automatically provide proper (.xtb that contains translations bundle for the current locale) .xtb to closure. 
For instance, we could generate .xtb bundles using apt like in https://github.com/treblereel/gwt3-processors/pull/17
> .xtb auto discovery

- build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java
- build-caching/src/main/java/com/vertispan/j2cl/build/TaskScheduler.java
This solves a bug where a task might be enqueued in the executor service
for longer than the stale timeout, so the cache believes that the
running task is in fact stale/canceled, and attempts to cancel it, but
this races against the task actually starting and trying to use the
files it expected to have access to.
Fixes #186
> When a task is ready to run and enqueued, mark it as started right away

- j2cl-maven-plugin/src/it/top-level-source-file/src/main/java/externs.js
In theory we should have gotten an error for this instead of a warning, but at least the tests confirmed that the file could be loaded at all.
> Correct externs so the compiler avoids a warning

- j2cl-maven-plugin/src/it/hello-world-web-components/src/main/webapp/index.html
With this path corrected, the test can again be manually confirmed.
> Fix a path in the (disabled) web component integration test

- .github/workflows/build.yml
- pom.xml
Builds will seem to work correctly until turbine or closure runs, as this commit doesn't actually change the language or bytecode level yet.
We should go a step further for the mojos and actually give a human readable error, if there is no way to otherwise have maven validate that the plugin requires Java 8.
> Drop support for Java 8, in anticipation of updating closure

- .circleci/config.yml
Likely this should be replaced with github actions, but for now this keeps snapshots working.
> Update circleci to a newer image format with Java 11

- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/BundleJarTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/Closure.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/J2cl.java
- pom.xml
This branch brings us up to Nov 2022 for closure-compiler, Aug 2022 for J2CL, but leaves our current closure-library dependency at Aug 2021 for now.
The closure-compiler fork includes changes for BUNDLE to avoid parsing JS files, but only scan for dependencies or ES6 modules that require transpilation in order to be bundled.
Updating closure-compiler adds a hard dependency on Java 11+, but we've already officially dropped support for Java 8 in this repository.
> Update J2CL and Closure dependencies

- j2cl-archetypes/README.md
While trying to run the archetypes, I found that the documentation used the wrong version numbers.
> Fix version number of archetypes in documentation

- j2cl-maven-plugin/src/it/elemental2-project/pom.xml
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/ClosureBundleTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/GwtIncompatiblePreprocessor.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/tools/J2cl.java
- pom.xml
Now using latest tagged j2cl, jsinterop-base, and the closure-compiler version that j2cl depends on.
Also updates elemental2 test to ensure the latest release works with the plugin.
Fixes #234
> Update dependencies from Google repos

- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/IJarTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/JavacTask.java
- j2cl-tasks/src/main/java/com/vertispan/j2cl/build/provided/TurbineTask.java
Formally deprecates old unused tasks that Turbine does for us now.
> Remove ability for Turbine to fall back to old implementation

- j2cl-maven-plugin/src/main/java/com/vertispan/j2cl/mojo/AbstractBuildMojo.java
See [Release Notes for 2.10.0](https://www.gwtproject.org/release-notes.html#Release_Notes_2_10_0)
> Maven` groupId is formally changed to org.gwtproject, projects should take care to make sure they are using either the old com.google.gwt:gwt BOM or the new org.gwtproject:gwt BOM to sure that Maven or Gradle correctly handle this change. This will be the last published version using the com.google.gwt groupId.
> Added GWT >= 2.10 replacements

- pom.xml
the latest turbine still has 8 source/target java levels, so there must be no issues
> bump turbine to 0.6.0
